### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by dcod3d** [joachimneumann/bisqremote_iOS#3]
iPhone XS, iOS 12.X 

First, force closing the app or re-pairing does not make a difference.

I get the push notification on my phone and clicking on it will show the message <50% of the time. The app will open with no new messages. Also, if I have multiple notifications, after I attempt to open one, all the others are cleared away and no possibility to get those messages. So overall, I can actually see at best 10% of my notifications. And these are all trade/dispute notifications,

**Comment by devinbileck** [comment]
@ncstdc would you be able to confirm if this issue still exists with the latest version 1.4? It has some fixes for notification issues.
Closing for now. Feel free to reopen if the issue still occurs.
